baseURL = "https://andrew-data-dev.github.io/"
languageCode = "en-us"
title = "andrew jacobson"
theme = "PaperMod"
pagerSize = 5

[params]

  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowPostTags = true

[taxonomies]

  tags = "tags"
  categories = "categories"

[menu]

  [[menu.main]]
  identifier = "about"
  name = "about"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "personal projects"
  name = "personal projects"
  url = "/personal_projects/"
  weight = 2

  [[menu.main]]
  identifier = "work projects"
  name = "work projects"
  url = "/work_projects/"
  weight = 3  

  [[menu.main]]
  identifier = "posts"
  name = "posts"
  url = "/posts/"
  weight = 4